languages:

- javascript
- typescript
- yaml
- css


files:
- "src/**/*"

exclude:
- "vendor/**/*.*"
- "**/*.min.js"
- "**/*.mm.js"
- "**/*/testUtils.ts"

reporter: xml

languages-exts:
  javascript:
  - es
  - es5
  - es6
  - es7
